server:
  port: 8080

spring:
  application:
    name: boot
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=VALUE
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2
    console.settings.trace: false
    console.settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

springdoc:
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

github:
  url: https://api.github.com/